```{r}
library(affy)
```





```{r}
wd <- getwd()
```

Now we can start reading in the files:

```{r}
datadir <- paste0(wd, "/rawdata-master")
basedir <- paste0(datadir, "/celfiles")
setwd(basedir)
library(affy)
tab <- read.delim("sampleinfo.txt",check.names=FALSE,as.is=TRUE)
rownames(tab) <- tab$filenames
tab
fns <- list.celfiles(basedir)
fns
fns %in% tab[,1] ##check
ab <- ReadAffy(filenames = file.path(basedir,tab[,1]),phenoData=tab)


```






```{r}

```

```{r}
dim(pm(ab))
```




6 samples along 17 metadatacolums
```{r}

dim(pData(ab))
```

name of genesid

```{r}

head(rownames(ab))
```


```{r}
rownames(pData(ab))
```

sample 1 to 6
```{r}

head(colnames(pm(ab)))
```

```{r}

annotation(ab)
```

```{r}
ab[,1:4]
```



```{r}
pData(ab[,1:4])
```
preprocess problevel information because we want to get gene level information and we will get expression data in result



```{r}
e <- rma(ab)    # preprocess probe-level data into gene-level data
dim(exprs(e))

#with single shot do it all
ejust <- justRMA(filenames=file.path(basedir,tab[,1]),phenoData=tab)    # read and process data to gene-level in one command
dim(ejust)
```

