
```{r,eval=false}
library(devtools)
install_github("genomicsclass/GSE5859Subset")
```

```{r}
library(GSE5859Subset)
data(GSE5859Subset)
dim(geneExpression)
```

```{r}
dim(geneAnnotation)
```

```{r}
dim(sampleInfo)
```

```{r}
all.equal(rownames(geneExpression),geneAnnotation$PROBEID)
```
seeing 

```{r}
all.equal(colnames(geneExpression),sampleInfo$filename)

```

```{r}
head(geneExpression)
```

```{r}
ls()
```



```{r}
head(geneAnnotation)
```

```{r}
head(geneExpression)
```

```{r}
rownames(sampleInfo)
```

```{r}
head(sampleInfo)
```
Expressing Requirement
```{r}
rownames(sampleInfo)=sampleInfo$filename
```



```{r}
head(rownames(geneAnnotation))
```

```{r}
head(geneAnnotation$PROBEID)
```

```{r}
rownames(geneAnnotation)=geneAnnotation$PROBEID
```


```{r}

library(Biobase)

```

```{r}
es5859 = ExpressionSet(assayData = geneExpression)
```

```{r}

#Phenotype Data
pData(es5859)= sampleInfo
#fearure data

fData(es5859)=geneAnnotation
```


```{r}
es5859
```
Why we do this we need to accelerate methods

```{r}
methods(class ="ExpressionSet")
```
Suppose I want 4 features and 3 samples


```{r}
es5859[1:4,1:3]
```

what to see to see the meta data of feature


```{r}
fData(es5859)[1:5,]
```
extract feature data having chromosome  = chrY

```{r}
length(which(fData(es5859)$CHR=="chrY"))
```
extact only those features having chromosome Y feature


```{r}

es5859[which(fData(es5859)$CHR=="chrY")]


```



```{r}
library(annotate)
```
```{r}

mi= pmid2MIAME("17206142")

```

```{r}
mi
```

```{r}
experimentData(es5859)=mi
```


Now You can see PubMediId
```{r}
es5859
```


```{r}
BiocManager::install("GEOquery")
```

```{r}
library(GEOquery)
```

```{r}
glioMA=getGEO("GSE78703")[[1]]
```

```{r}
glioMA
```


metadata for samples
```{r}
names(pData(glioMA))
```
```{r}
glioMA$molecule_ch1
```

```{r}
table(glioMA$`treated with:ch1`, glioMA$`cell type:ch1`)
```

